export default {
    name:'contacto',
    title:'Contacto',
    type:'document',
    fields:[
        {
            name:'nombre',
            title:'Nombre',
            type:'string'
        },
        {
            name:'email',
            title:'Email',
            type:'string'
        },
        {
            name:'mensaje',
            title:'Mensaje',
            type:'text'
        }
    ]
}